<div class="container-fluid mb-5"> 
    <div class="row">
        <div class="col-lg-6">
            <form method="post">
                <input type="hidden" name="song_id" value="<?=$songParameters['song_id']?>" />
                <div class="form-group">
                    <label for="artist">Jméno autora</label>
                    <input type="text" class="form-control" name="artist" id="artist" value="<?=$songParameters['artist']?>">
                </div>   
                <div class="form-group">
                    <label for="title">Název</label>
                    <input type="text" class="form-control" id="title" name="title" value="<?=$songParameters['title']?>">
                </div>  
                <div class="form-group">
                    <label for="lyrics">Text písně s akordy</label>
                    <textarea rows="10" id="lyrics" class="form-control" name="lyrics"><?=$songParameters['lyrics']?></textarea>
                </div>  
                <div class="form-group">
                    <label for="url">URL</label>
                    <input id="url" class="form-control" name="url" value="<?=$songParameters['url']?>">
                </div> 
                <div class="form-group">
                    <label for="strumming_pattern">Vzor brnkání - vkládejte &darr;, &uarr; a -</label>
                    <input type="text" id="strumming_pattern" class="form-control" name="strumming_pattern" value="<?=$songParameters['strumming_pattern']?>">
                </div>     
                <div class="form-group">
                    <label for="dropdown">Vyberte akordy</label>
                    <select class="form-control" id="dropdown" name="dropdown1">
                        <option disabled selected value>--Vyberte si akord--</option>
                        <?php foreach ($chords as $chord1): ?>
                            <option value="<?= $chord1 ?>"><?= $chord1 ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <select class="form-control" name="dropdown2">
                        <option disabled selected value>--Vyberte si akord--</option>
                        <?php foreach ($chords as $chord2): ?>
                            <option value="<?= $chord2 ?>"><?= $chord2 ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <select class="form-control" name="dropdown3">
                        <option disabled selected value>--Vyberte si akord--</option>
                        <?php foreach ($chords as $chord3): ?>
                            <option value="<?= $chord3 ?>"><?= $chord3 ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <select class="form-control" name="dropdown4">
                        <option disabled selected value>--Vyberte si akord--</option>
                        <?php foreach ($chords as $chord4): ?>
                            <option value="<?= $chord4 ?>"><?= $chord4 ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <select class="form-control" name="dropdown5">
                        <option disabled selected value>--Vyberte si akord--</option>
                        <?php foreach ($chords as $chord5): ?>
                            <option value="<?= $chord5 ?>"><?= $chord5 ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <button type="submit" class="btn btn-secondary">Vložit píseň</button>
            </form>
        </div>
    </div>
</div>