<h2>Přihlášení do administrace</h2>

<div class="row">
    <div class="col-lg-4">
        <form method="post">
            <div class="form-group">
                <label for="name">Vaše přihlašovací jméno</label>
                <input type="text" class="form-control" id="name" name="name">
            </div>
            <div class="form-group">
                <label for="password">Vaše heslo</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>
            <button type="submit" class="btn btn-primary">Přihlásit</button>
        </form>
    </div>
</div>