<!doctype html>
<html lang="cs-cz">
    <head>
        <base href="/localhost" />
        <meta charset="utf-8">
        <title><?= $title ?></title>
        <meta name="description" content="<?= $description ?>" />
        <meta name="keywords" content="<?= $keywords ?>" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>

    <body style="padding-bottom: 50px">
        <?php foreach ($messages as $message): ?>
            <div role="alert" class="alert alert-<?= $message['style'] ?>">
                <?= $message['message'] ?>
            </div>
        <?php endforeach; ?>
        <div class="container w-75 mb-3">
            <nav class="navbar bg-light navbar-expand-sm">
                <a class="navbar-brand" href="about">
                    <img src="images/logo.png" class="d-inline-block align-top" width="64" height="64" alt="chords page">
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-content" aria-controls="obsah-navigacni-listy" aria-expanded="false" aria-label="Rozbalit navigaci">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar-content">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="about">O stránce<span class="sr-only">O naší stránce</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="song">Výběr písničky</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="editor">Vložení písničky</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="contact">Kontakt</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <div class="container w-75">
            <article>
                <?php $this->controller->renderView(); ?>
            </article>
        </div>    
        <footer class="fixed-bottom">
            <div class="text-center bg-light p-4" style="background-color: rgba(0, 0, 0, 1);">
                <a href="logIn">Přihlášení</a> |
                <a href="administration">Administrace</a>
            </div>
        </footer>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>